### ISSUE TITLE
Unable to fulfill the dependency

### ISSUE THREAD

**Issue by mudrd8mz** [JotaDF/moodle-availability_game#1]
The plugin declares a dependency:

https://github.com/JotaDF/moodle-availability_game/blob/2055aeb13759bde19ebdd66cb366166f9609bd3a/version.php#L33

but the block_game has latest available version in the plugins directory 2021033029. The required version 2021033030 was not released yet. As a consequence, this availability plugin cannot be installed.

**Comment by JotaDF** [comment]
You're right, I thought I had uploaded version 2021033030 to the repository, but I only uploaded it to github. I will correct it now.
