### ISSUE TITLE
Incorrect DB API usage

### ISSUE THREAD

**Issue by danmarsden** [JotaDF/moodle-availability_game#2]
variables must be passed as placeholders to the Moodle DB API functions to prevent sql injection vulnerabilities:

https://github.com/JotaDF/moodle-availability_game/blob/main/classes/condition.php#L148

More information on this is available herE:
https://docs.moodle.org/dev/Data_manipulation_API#Placeholders

Please review all your custom SQL statements and ensure they are using placeholders - please note this is a blocker for approval in the plugins db - thanks!

**Comment by JotaDF** [comment]
Hi Dan,
Fixed SQL.
Thanks for the collaboration.
